### ISSUE TITLE
Not supported options "count_of_rows, dialect, hash"

### ISSUE THREAD

**Issue by zelima** [datahq/datapackage-pipelines-datahub#3]
When trying to publish package with datapackage.json that has "count_of_rows, dialect, hash" keys the `data push ...` command exits with 0 (works fine), but Pipeline fails with following error `tabulator.exceptions.OptionsError: Not supported options "count_of_rows, dialect, hash"` 

## Acceptance criteria

* [ ] able to push and see it live

## Tasks

* [ ] remove items above fro  datapackage.sjon before push

# Analysis 

Full stack

```
WARNING :Error while opening resource from url https://s3.amazonaws.com/rawstore-testing.datahub.io/da2ccf20ffd1709aed2bd85b91b04fa6: OptionsError('Not supported options "count_of_rows, dialect, hash" for scheme "https" and format "csv"',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/datapackage_pipelines/specs/../lib/stream_remote_resources.py", line 201, in 
    rows = stream_reader(resource, url, ignore_missing or url == "")
  File "/usr/local/lib/python3.6/site-packages/datapackage_pipelines/specs/../lib/stream_remote_resources.py", line 159, in stream_reader
    schema, headers, stream, close = get_opener(url, _resource)()
  File "/usr/local/lib/python3.6/site-packages/datapackage_pipelines/specs/../lib/stream_remote_resources.py", line 144, in opener
    _stream.open()
  File "/usr/local/lib/python3.6/site-packages/tabulator/stream.py", line 141, in open
    raise exceptions.OptionsError(message)
tabulator.exceptions.OptionsError: Not supported options "count_of_rows, dialect, hash" for scheme "https" and format "csv"
```
Simplest and quickest solution would be to just remove that keys for datapackage.json

**Comment by zelima** [comment]
FIXED/INVALID fix in https://github.com/frictionlessdata/datapackage-pipelines/commit/361ae110facd172c1e46a4aa3962d39f8f15e782
